services:
  payment-db:
    image: postgres:15
    container_name: payment-db
    restart: always
    environment:
      POSTGRES_DB: payment_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "15436:5432"
    volumes:
      - payment-db-data:/var/lib/postgresql/data

volumes:
  payment-db-data: