services:
  product-db:
    image: postgres:15
    container_name: product-db
    restart: always
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "15434:5432"
    volumes:
      - product-db-data:/var/lib/postgresql/data

  product-redis:
    image: redis:7
    container_name: product-redis
    restart: always
    ports:
      - "6381:6379"

volumes:
  product-db-data: