version: '3.8'

services:
  user-db:
    image: postgres:15
    container_name: user-db
    restart: always
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "15433:5432"
    volumes:
      - user-db-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: user-redis
    restart: always
    ports:
      - "6380:6380"

  adminer:
    image: adminer
    container_name: user-adminer
    restart: always
    ports:
      - "8082:8080"
    depends_on:
      - user-db

volumes:
  user-db-data: